apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentapp-sa
  namespace: ai-workshop
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: f2a88090-a6f5-438d-976f-63b1f0fc29ae
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agentapp-role
  namespace: ai-workshop
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentapp-rolebinding
  namespace: ai-workshop
subjects:
- kind: ServiceAccount
  name: agentapp-sa
  namespace: ai-workshop
roleRef:
  kind: Role
  name: agentapp-role
  apiGroup: rbac.authorization.k8s.io